name: Linux, Windows, macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: mkdir
        run: mkdir build

      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: 7033f94778e81f6a62ce46639c07393f95b50c89
          path: vcpkg

      - name: Setup vcpkg (Windows)
        run: ./vcpkg/bootstrap-vcpkg.bat
        if: matrix.os == 'windows-latest'

      - name: "Setup vcpkg (non Windows)"
        run: ./vcpkg/bootstrap-vcpkg.sh
        if: matrix.os != 'windows-latest'

      - name: configure (with vcpkg on Windows)
        working-directory: ./build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="vcpkg\scripts\buildsystems\vcpkg.cmake" ..
        shell: cmd
        if: matrix.os == 'windows-latest'

      - name: configure (with vcpkg on non-Windows)
        working-directory: ./build
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake" ..
        if: matrix.os != 'windows-latest'

      - name: build
        working-directory: ./build
        run: cmake --build .

#      - name: test
#        working-directory: ./build
#        run: ctest -C Debug .
